#! /bin/bash

# description: This shell script takes care of starting and stopping chatroom_server

# Source function library.
. /etc/init.d/functions

#the serbice name for example: chatroom_server
SNAME=chatroom_server

#the full path and name of the daemon program
#Warning:The name of executable file must be identical with service name
PROG=/usr/bin/$SNAME

#start function
start()
{
    #check the daemon status first
    if [ -f /var/lock/subsys/$SNAME ]
    then
        echo "$SNAME is already started!"
        exit 0
    else 
        action "Starting $SNAME is ..." $PROG
        [ $? -eq 0 ] && touch /var/lock/subsys/$SNAME
        exit 0
    fi
}

#stop function
stop()
{
    echo "Stopping $SNAME ..."
    killproc $SNAME
    rm -rf /var/lock/subsys/$SNAME
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
reload|restart)
    stop
    start
    ;;
status)
    status $SNAME
    ;;
*)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 1
esac
